name: CCMMobileMVP
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  CCMMobileMVP:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: CCMMobileMVP
    info:
      path: CCMMobileMVP/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.local.CCMMobileMVP
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    scheme:
      gatherCoverageData: false
